#!/usr/bin/env bash
# install a Web server

sudo apt-get -y update
sudo apt-get -y install nginx
service nginx start
echo Holberton School | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
