#!/usr/bin/env bash
#Replace a line with multiple lines with sed
#cambia la line 46 (está en mi location en el file default) por lo q le paso
#sed -i "s/string_to_replace/$new_string/" file
#new_string="line number 1\nline number 2\nline number 3"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "46i rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart
