#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the
#...string Ceci n'est pas une page

FILE=/etc/nginx/sites-available/default
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
sudo sed -i "33i error_page 404 /custom_404.html;\n location = /custom_404.html {\n root /usr/share/nginx/html;\n internal;\n}\n" $FILE
sudo service nginx restart
