#!/usr/bin/env bash
#1. configure web-02 to be identical to web-01
#2. add a custom Nginx response header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "23i \add_header X-Served-By \$hostname always;" /etc/nginx/sites-available/default
sudo service nginx restart
