#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
# Set ENABLED to 1 if you want the init script to start haproxy
# $a queda en la última parte del archivo que se vaya a modificar

sudo apt-get update
sudo apt-get install -y haproxy=1.6.\*
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
echo -e "\nfrontend haproxynode\n\tbind *:80\n\tmode http\n\tdefault_backend backendnodes\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "backend backendnodes\n\tbalance roundrobin\n\tserver 1529-web-01 34.75.110.174:80 check\n\tserver 1529-web-02 34.73.253.210:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
