#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

apt-get update
apt-get install haproxy=1.6.\*
apt-get install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.6
apt-get update
apt-get install haproxy=1.6.\*
sudo cp -p /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sudo sed -i "36i \nfrontend firstbalance\n\tbind *:80\n\toption forwardfor\n\tdefault_backend webservers\n\n\tbackend webservers\n\tbalance roundrobin\n\tserver 1529-web-01 34.75.110.174:80 check\n\tserver 1529-web-02 34.73.253.210:80 check\n\toption httpchk;" /etc/haproxy/haproxy.cfg
sudo service haproxy start
