#!/usr/bin/env bash
# pings an IP address passed as an argument
# accepts a string as an argument
# ping the IP 5 times
# -c count
# $1 = “arg_1” (positional argument 1)

if [ "$1" == "" ]; 
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi
