#!/usr/bin/env bash
# displays lines containing the bash word, thus allowing you to easily get...
# ...the PID of your Bash process
# -e this can be used to specify multiple search  patterns
# shellcheck disable=SC2009

ps aux | grep -e bash