#!/usr/bin/env bash
# displays:
# -To infinity and beyond indefinitely
# -With a sleep 2 in between each iteration
# -I am invincible!!! when receiving a SIGTERM signal

function sigproc() {
	echo "I am invincible!!!"
}

trap sigproc SIGTERM

while :
do
	echo "To infinity and beyond"
	sleep 2
done