#!/usr/bin/env bash
#displays Holberton School 10 times, but for the 9th iteration, displays
#Holberton School and then Hi on a new line

counter=1
finished=10
while [ $finished -ge $counter ]
do
  echo "Holberton School"
  if [ $counter == 9 ]
  then 
    echo "Hi"
  fi
  let counter=$counter+1
done