#!/usr/bin/env bash
counter=1
finished=20
while [ $counter -le $finished ]
do
    echo "$counter"
    case $counter in 
        4)echo "bad luck from China";;
        9)echo "bad luck from Japan";;
        17)echo "bad luck from Italy";;
    esac
    counter=$((counter += 1))
done