#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes

hours=0
minuts=1
while [ "$hours" -le 12 ]
do
    echo "Hour: $hours"
    while [ "$minuts" -le 59 ]
    do
        echo "$minuts"
        ((minuts++))
    done
    minuts=1
    ((hours++))
done