#!/usr/bin/env bash
# should run the whoami command under the user passed as an argument
i_am=$(sudo -u "$1" whoami)                                                                                                               
echo "$i_am"
