#!/usr/bin/env bash
# should run the whoami command under the user passed as an argument
echo "$1"                                                                                                               
