#!/usr/bin/env bash
# should run the whoami command under the user passed as an argument
i_am=$(sudo id -u -n "$1")                                                                                                               
echo "$i_am"
