#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server ipv6only=on;/listen \[::\]:8080 default_server ipv6only=on;/' /etc/nginx/sites-available/default
chmod 755 /etc/nginx/nginx.conf
pkill apache2
sudo service nginx restart
